---
title: "Analysis of Access to Electricity and National Income"
author: "Iman"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

```{r edu_setup, message=FALSE, echo = FALSE, warning=FALSE}
pkgs <- c("here","dplyr","ggplot2","sf","rnaturalearth","rnaturalearthdata","leaflet","broom","knitr","tidyr","scales","rmarkdown")
missing_pkgs <- setdiff(pkgs, rownames(installed.packages()))
if (length(missing_pkgs) > 0) install.packages(missing_pkgs)
lapply(pkgs, library, character.only = TRUE)

```

```{r ep1}
data_merged <- readRDS(here("Data", "Processed", "data_merged.RDS"))
data_grouped <- readRDS(here("Data", "Processed", "data_grouped.RDS"))
data_electricity <- left_join(data_merged, data_grouped, by = c("Country Name", "Country Code"))

```

```{r ep2}
world <- ne_countries(scale = "medium", returnclass = "sf")
data_continent <- data_electricity %>%
  left_join(world %>% select(admin, continent), by = c("Country Name" = "admin")) %>%
  mutate(continent = if_else(continent == "North America", "US", continent)) %>%
  filter(!is.na(continent))
ep1 <- ggplot(data_continent, aes(x = Year, y = EG.ELC.ACCS.ZS, color = continent)) +
  stat_summary(fun = "mean", geom = "line") +
  labs(title = "Trends in Access to Electricity by Continent",
       x = "Year",
       y = "Access to Electricity (%)",
       color = "Continent") +
  scale_color_brewer(palette = "Set2") +
  theme_bw()

ep1
```

```{r ep3}
data_density <- data_electricity %>%
  filter(!is.na(EN.POP.DNST)) %>%
  mutate(pop_density_cat_num = ntile(EN.POP.DNST, 3),
         pop_density_cat = factor(pop_density_cat_num, levels = 1:3,
                                  labels = c("Niedrig", "Mittel", "Hoch")))
ep2 <- ggplot(data_density, aes(x = Year, y = EG.ELC.ACCS.ZS, color = pop_density_cat, group = pop_density_cat)) +
  stat_summary(fun = "mean", geom = "line") +
  labs(title = "Trend in Access to Electricity by Population Density",
       x = "Year",
       y = "Access to Electricity (%)",
       color = "Population Density Category") +
  scale_color_brewer(palette = "Set2") +
  theme_bw()

ep2
```

```{r ep4}
data_incomes <- data_electricity %>%
  filter(!is.na(NY.ADJ.NNTY.PC.CD)) %>%
  mutate(income_group_num = ntile(NY.ADJ.NNTY.PC.CD, 5),
         income_group = factor(income_group_num, levels = 1:5,
                               labels = c("Sehr gering", "Gering", "Mittel", "Groß", "Sehr groß")))
ep3 <- ggplot(data_incomes, aes(x = NY.ADJ.NNTY.PC.CD, y = EG.ELC.ACCS.ZS)) +
  geom_point(aes(color = income_group), alpha = 0.6) +
  geom_smooth(method = "loess", se = FALSE, color = "black") +
  scale_x_log10(labels = comma) +
  labs(title = "Income vs. Access to Electricity",
       x = "Income per Capita (USD, log scale)",
       y = "Access to Electricity (%)",
       color = "Einkommens-Gruppe") +
  theme_bw() +
  scale_colour_brewer(palette = "Set2")

ep3
```

```{r ep5}
data_surface <- data_electricity %>%
  filter(!is.na(AG.SRF.TOTL.K2)) %>%
  mutate(surface_area_cat_num = ntile(AG.SRF.TOTL.K2, 3),
         surface_area_cat = factor(surface_area_cat_num, levels = 1:3,
                                   labels = c("Niedrig", "Mittel", "Hoch")))
ep4 <- ggplot(data_surface, aes(x = surface_area_cat, y = EG.ELC.ACCS.ZS)) +
  geom_boxplot(fill = "skyblue", alpha = 0.7, outlier.color = "red") +
  labs(title = "Access to Electricity by Surface Area Category",
       x = "Surface Area Category",
       y = "Access to Electricity (%)") +
  theme_minimal()
ep4
```

```{r ep6}
world_map <- ne_countries(scale = "medium", returnclass = "sf")
world_data <- world_map %>%
  left_join(data_electricity, by = c("iso_a3" = "Country Code"))
ep5 <- ggplot(world_data) +
  geom_sf(aes(fill = EG.ELC.ACCS.ZS), color = "black", size = 0.1) +
  scale_fill_distiller(palette = "YlGn", direction = 1, na.value = "lightgrey",
                       name = "Access to Electricity (%)") +
  labs(title = "Global Access to Electricity") +
  theme_bw()
ep5
```

```{r ep7}
lm_model <- lm(EG.ELC.ACCS.ZS ~ NY.ADJ.NNTY.PC.CD  + AG.SRF.TOTL.K2, data = data_electricity)
kable(tidy(lm_model), caption = "Linear Regression Results")

```
